"""empty message

Revision ID: 13a07305a6f
Revises: 5886af9f1b8
Create Date: 2015-02-28 15:52:09.372233

"""

# revision identifiers, used by Alembic.
revision = '13a07305a6f'
down_revision = '5886af9f1b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###
