"""empty message

Revision ID: 160f2bee6fa
Revises: 2cbf9c6821b
Create Date: 2015-03-01 23:32:06.382769

"""

# revision identifiers, used by Alembic.
revision = '160f2bee6fa'
down_revision = '2cbf9c6821b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
