"""empty message

Revision ID: 1619379ed0c
Revises: bd93120755
Create Date: 2015-02-27 00:31:11.132357

"""

# revision identifiers, used by Alembic.
revision = '1619379ed0c'
down_revision = 'bd93120755'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
