"""empty message

Revision ID: 171244bc952
Revises: 4394c00328f
Create Date: 2015-03-01 14:23:24.567287

"""

# revision identifiers, used by Alembic.
revision = '171244bc952'
down_revision = '4394c00328f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
