"""empty message

Revision ID: 1a163d3f0d7
Revises: 46c70e0e089
Create Date: 2015-02-28 15:15:17.961304

"""

# revision identifiers, used by Alembic.
revision = '1a163d3f0d7'
down_revision = '46c70e0e089'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stat_recorded_at_key', 'stat', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('stat_recorded_at_key', 'stat', ['recorded_at'])
    ### end Alembic commands ###
