"""empty message

Revision ID: 1cf81d9509f
Revises: 2c7418044df
Create Date: 2015-02-27 13:46:49.710443

"""

# revision identifiers, used by Alembic.
revision = '1cf81d9509f'
down_revision = '2c7418044df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ent_name', sa.String(length=255), nullable=False),
    sa.Column('ent_unit', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enterprise')
    ### end Alembic commands ###
