"""empty message

Revision ID: 220cc41ccc3
Revises: 2f31cf5fcaf
Create Date: 2015-03-02 22:43:31.170958

"""

# revision identifiers, used by Alembic.
revision = '220cc41ccc3'
down_revision = '2f31cf5fcaf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_goal', sa.Column('value', sa.Integer(), nullable=False))
    op.drop_column('unit_goal', 'units')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_goal', sa.Column('units', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('unit_goal', 'value')
    ### end Alembic commands ###
