"""empty message

Revision ID: 22e559aaea2
Revises: c0fd22a946
Create Date: 2015-03-02 07:22:03.294992

"""

# revision identifiers, used by Alembic.
revision = '22e559aaea2'
down_revision = 'c0fd22a946'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
