"""empty message

Revision ID: 2384594e6b5
Revises: 160f2bee6fa
Create Date: 2015-03-01 23:33:17.240676

"""

# revision identifiers, used by Alembic.
revision = '2384594e6b5'
down_revision = '160f2bee6fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
