"""empty message

Revision ID: 2cbf9c6821b
Revises: 277dbc12983
Create Date: 2015-03-01 23:24:48.499476

"""

# revision identifiers, used by Alembic.
revision = '2cbf9c6821b'
down_revision = '277dbc12983'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
