"""empty message

Revision ID: 2f31cf5fcaf
Revises: fb4bb1d807
Create Date: 2015-03-02 22:38:52.274369

"""

# revision identifiers, used by Alembic.
revision = '2f31cf5fcaf'
down_revision = 'fb4bb1d807'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
