"""empty message

Revision ID: 2fbc607fe80
Revises: 81834e479
Create Date: 2015-02-28 18:08:25.080617

"""

# revision identifiers, used by Alembic.
revision = '2fbc607fe80'
down_revision = '81834e479'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_goal')
    ### end Alembic commands ###
