"""empty message

Revision ID: 37e19b58682
Revises: 34d457ba511
Create Date: 2015-02-27 15:38:35.972057

"""

# revision identifiers, used by Alembic.
revision = '37e19b58682'
down_revision = '34d457ba511'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
