"""empty message

Revision ID: 3f88f89198f
Revises: 1cf81d9509f
Create Date: 2015-02-27 21:38:03.681698

"""

# revision identifiers, used by Alembic.
revision = '3f88f89198f'
down_revision = '1cf81d9509f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recorded_at')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stat')
    ### end Alembic commands ###
