"""empty message

Revision ID: 41b760ab0d4
Revises: 13a07305a6f
Create Date: 2015-03-01 23:10:45.439468

"""

# revision identifiers, used by Alembic.
revision = '41b760ab0d4'
down_revision = '13a07305a6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
