"""empty message

Revision ID: 452802fa1b1
Revises: 1619379ed0c
Create Date: 2015-02-27 16:02:29.951081

"""

# revision identifiers, used by Alembic.
revision = '452802fa1b1'
down_revision = '1619379ed0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
