"""empty message

Revision ID: 46c70e0e089
Revises: 3f88f89198f
Create Date: 2015-02-28 11:50:09.646566

"""

# revision identifiers, used by Alembic.
revision = '46c70e0e089'
down_revision = '3f88f89198f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
