"""empty message

Revision ID: 5886af9f1b8
Revises: 15fe3994a54
Create Date: 2015-02-28 15:09:31.379371

"""

# revision identifiers, used by Alembic.
revision = '5886af9f1b8'
down_revision = '15fe3994a54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('activity', 'activity')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('activity', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('activity', 'name')
    ### end Alembic commands ###
