"""empty message

Revision ID: c0fd22a946
Revises: None
Create Date: 2015-02-28 16:01:43.793939

"""

# revision identifiers, used by Alembic.
revision = 'c0fd22a946'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_name', sa.String(length=255), nullable=False),
    sa.Column('t_type', sa.Integer(), nullable=False),
    sa.Column('t_units', sa.String(length=255), nullable=False),
    sa.Column('t_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['t_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tr_value', sa.Integer(), nullable=False),
    sa.Column('tr_beg_value', sa.Integer(), nullable=True),
    sa.Column('tr_end_value', sa.Integer(), nullable=True),
    sa.Column('tr_target_date', sa.Date(), nullable=True),
    sa.Column('tr_date', sa.Date(), nullable=False),
    sa.Column('tr_task_id', sa.Integer(), nullable=True),
    sa.Column('tr_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tr_task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['tr_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking')
    op.drop_table('task')
    op.drop_table('user')
    ### end Alembic commands ###
