"""empty message

Revision ID: fb4bb1d807
Revises: 2fbc607fe80
Create Date: 2015-03-02 22:00:20.826080

"""

# revision identifiers, used by Alembic.
revision = 'fb4bb1d807'
down_revision = '2fbc607fe80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
